export const GET_PRODUCTS_LOAD ="GET_PRODUCT_LOAD";
export const GET_PRODUCTS_FAIL ="GET_PRODUCT_FAIL";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCT_SUCCESS";

export const GET_PRODUCT= 'GET_PRODUCT';
export const EDIT_PRODUCT= "EDIT_PRODUCT";
export const TOGGLE_FALSE="TOGGLE_FALSE";
export const TOGGLE_TRUE="TOGGLE_TRUE";

